server:
  port: 8088
hbase:
  zkQuorum: 172.16.4.4,172.16.4.5,172.16.4.6
  zkPort: 2181
  rootDir: hdfs://cstdevcluster/hbase
  zkDataDir:
hadoop:
  hadoopHomeDir: D:\hadoop\hadoop-2.6.5
  hadoopCoreFile:
    - hadoop/core-site.xml
    - hadoop/mapred-site.xml
    - hadoop/yarn-site.xml
    - hadoop/hdfs-site.xml
  crossPlatform: true
  ubertask: true
mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.cst.bigdata.domain.mybatis
spring:
  hadoop:
      config:
        fs:
          defaultFS: hdfs://cstdevcluster:8020
  datasource:
    name: dev
    url: jdbc:mysql://172.16.4.12:3306/stream?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: cst2008
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: true
  rowBoundsWithCount: false
swagger:
  description: xuexiwenjian
  version: 1.0.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: http://localhost:8088/swagger-ui.html
  base-package: com.cst.bigdata
  docket:
    xiaoq:
      title: group-a
      version: 1.0.0

